// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-KXuxbw8oOGCyH7IF6TaQBTcnSSN54dQ',
    appId: '1:506944482241:web:02b97307bc2806cc6d1d40',
    messagingSenderId: '506944482241',
    projectId: 'sda-explorers-app',
    authDomain: 'sda-explorers-app.firebaseapp.com',
    storageBucket: 'sda-explorers-app.appspot.com',
    measurementId: 'G-HMZJXNGMXP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCT5XP1HGGnUiDDl9BtJckcRb-IN3zlsEY',
    appId: '1:506944482241:android:79583e2e7e1d47c26d1d40',
    messagingSenderId: '506944482241',
    projectId: 'sda-explorers-app',
    storageBucket: 'sda-explorers-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4J8CyVfpTQJSAjndFNHGcpY7bBIw4ALQ',
    appId: '1:506944482241:ios:14fdac3f62120d936d1d40',
    messagingSenderId: '506944482241',
    projectId: 'sda-explorers-app',
    storageBucket: 'sda-explorers-app.appspot.com',
    iosBundleId: 'com.example.sdaExplorersApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4J8CyVfpTQJSAjndFNHGcpY7bBIw4ALQ',
    appId: '1:506944482241:ios:14fdac3f62120d936d1d40',
    messagingSenderId: '506944482241',
    projectId: 'sda-explorers-app',
    storageBucket: 'sda-explorers-app.appspot.com',
    iosBundleId: 'com.example.sdaExplorersApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-KXuxbw8oOGCyH7IF6TaQBTcnSSN54dQ',
    appId: '1:506944482241:web:83a10459f6d6667c6d1d40',
    messagingSenderId: '506944482241',
    projectId: 'sda-explorers-app',
    authDomain: 'sda-explorers-app.firebaseapp.com',
    storageBucket: 'sda-explorers-app.appspot.com',
    measurementId: 'G-8YWHJXFCQQ',
  );
}
