// ignore_for_file: constant_identifier_names

import 'package:flutter/material.dart';
import 'package:sda_explorers_app/presentation/screens/Bible/bible_screen.dart';

enum BB {
  Genesis,
  Exodus,
  Leviticus,
  Numbers,
  Deuteronomy,
  Joshua,
  Judges,
  Ruth,
  Samuel1,
  Samuel2,
  Kings1,
  Kings2,
  Chronicles1,
  Chronicles2,
  Ezra,
  Nehemiah,
  Esther,
  Job,
  Psalms,
  Proverbs,
  Ecclesiastes,
  SongOfSolomon,
  Isaiah,
  Jeremiah,
  Lamentations,
  Ezekiel,
  Daniel,
  Hosea,
  Joel,
  Amos,
  Obadiah,
  Jonah,
  Micah,
  Nahum,
  Habakkuk,
  Zephaniah,
  Haggai,
  Zechariah,
  Malachi,
  Matthew,
  Mark,
  Luke,
  John,
  Acts,
  Romans,
  Corinthians1,
  Corinthians2,
  Galatians,
  Ephesians,
  Philippians,
  Colossians,
  Thessalonians1,
  Thessalonians2,
  Timothy1,
  Timothy2,
  Titus,
  Philemon,
  Hebrews,
  James,
  Peter1,
  Peter2,
  John1,
  John2,
  John3,
  Jude,
  Revelation,
}

const BibliaBookName = {
  BB.Genesis: "Genesis",
  BB.Exodus: "Exodo",
  BB.Leviticus: "Levitico",
  BB.Numbers: "Mga Bilang",
  BB.Deuteronomy: "Deuteronomio",
  BB.Joshua: "Josue",
  BB.Judges: "Mga Hukom",
  BB.Ruth: "Ruth",
  BB.Samuel1: "1 Samuel",
  BB.Samuel2: "2 Samuel",
  BB.Kings1: "1 Mga Hari",
  BB.Kings2: "2 Mga Hari",
  BB.Chronicles1: "1 Mga Cronica",
  BB.Chronicles2: "2 Mga Cronica",
  BB.Ezra: "Ezra",
  BB.Nehemiah: "Nehemias",
  BB.Esther: "Ester",
  BB.Job: "Job",
  BB.Psalms: "Mga Awit",
  BB.Proverbs: "Mga Kawikaan",
  BB.Ecclesiastes: "Ang Mangangaral",
  BB.SongOfSolomon: "Ang Awit ni Solomon",
  BB.Isaiah: "Isaias",
  BB.Jeremiah: "Jeremias",
  BB.Lamentations: "Mga Panaghoy",
  BB.Ezekiel: "Ezekiel",
  BB.Daniel: "Daniel",
  BB.Hosea: "Hosea",
  BB.Joel: "Joel",
  BB.Amos: "Amos",
  BB.Obadiah: "Obadias",
  BB.Jonah: "Jonas",
  BB.Micah: "Mikas",
  BB.Nahum: "Nahum",
  BB.Habakkuk: "Habakkuk",
  BB.Zephaniah: "Zefanias",
  BB.Haggai: "Hagai",
  BB.Zechariah: "Zacarias",
  BB.Malachi: "Malakias",
  BB.Matthew: "Mateo",
  BB.Mark: "Marcos",
  BB.Luke: "Lucas",
  BB.John: "Juan",
  BB.Acts: "Mga Gawa",
  BB.Romans: "Mga Taga-Roma",
  BB.Corinthians1: "1 Mga Taga-Corinto",
  BB.Corinthians2: "2 Mga Taga-Corinto",
  BB.Galatians: "Mga Taga-Galacia",
  BB.Ephesians: "Mga Taga-Efeso",
  BB.Philippians: "Mga Taga-Filipos",
  BB.Colossians: "Mga Taga-Colosas",
  BB.Thessalonians1: "1 Mga Taga-Tesalonica",
  BB.Thessalonians2: "2 Mga Taga-Tesalonica",
  BB.Timothy1: "1 Timoteo",
  BB.Timothy2: "2 Timoteo",
  BB.Titus: "Tito",
  BB.Philemon: "Filemon",
  BB.Hebrews: "Mga Hebreo",
  BB.James: "Santiago",
  BB.Peter1: "1 Pedro",
  BB.Peter2: "2 Pedro",
  BB.John1: "1 Juan",
  BB.John2: "2 Juan",
  BB.John3: "3 Juan",
  BB.Jude: "Judas",
  BB.Revelation: "Pahayag",
};

String? getTagalogName(BB book) {
  return BibliaBookName[book];
}

navigateToBible(BuildContext context, String code) {
  var map = BibleVerseAddress[code];
  if (map != null) {
    var bookName = getTagalogName(map['book'] as BB);
    if (bookName != null) {
      Navigator.push(
          context,
          MaterialPageRoute(
              builder: (context) => BibleScreen(
                  book: bookName,
                  chapter: map['chapter'] as int,
                  verse: map['verse'] as int)));
    }
  }
  print(code);
}

const BibleVerseAddress = {
  'L1M2': {'book': BB.Genesis, 'chapter': 1, 'verse': 1},
  'L1B8': {'book': BB.Genesis, 'chapter': 1, 'verse': 1},
  'L1B11': {'book': BB.Hebrews, 'chapter': 1, 'verse': 1},
  'L1B14': {'book': BB.Genesis, 'chapter': 1, 'verse': 2},
  'L1B19': {'book': BB.Matthew, 'chapter': 28, 'verse': 19},
  'L1B23': {'book': BB.Psalms, 'chapter': 53, 'verse': 1},
  'L1B28': {'book': BB.Genesis, 'chapter': 1, 'verse': 11},
  'L1B29': {'book': BB.Genesis, 'chapter': 1, 'verse': 25},
  'L1B32': {'book': BB.Genesis, 'chapter': 1, 'verse': 27},
  'L1B36': {'book': BB.Genesis, 'chapter': 1, 'verse': 16},
  'L1B38': {'book': BB.Psalms, 'chapter': 19, 'verse': 1},
  'L1B39': {'book': BB.Psalms, 'chapter': 8, 'verse': 3},
  'L1B43': {'book': BB.Psalms, 'chapter': 33, 'verse': 6},
  'L1B46': {'book': BB.Hebrews, 'chapter': 11, 'verse': 3},
  'L1B51': {'book': BB.Genesis, 'chapter': 2, 'verse': 1},
  'L1B52': {'book': BB.Job, 'chapter': 38, 'verse': 4},
  'L1B56': {'book': BB.Ecclesiastes, 'chapter': 12, 'verse': 11},
  'L1B59': {'book': BB.Timothy2, 'chapter': 3, 'verse': 15},
  'L1B61': {'book': BB.Ecclesiastes, 'chapter': 12, 'verse': 13},
   'L2M2': {'book': BB.Timothy2, 'chapter': 3, 'verse': 16},
   'L2B7': {'book': BB.Peter2, 'chapter': 1, 'verse': 20},
   'L2B11': {'book': BB.John, 'chapter': 5, 'verse': 39},
   'L2B14': {'book': BB.John, 'chapter': 17, 'verse': 17},
   'L2B17': {'book': BB.Timothy2, 'chapter': 3, 'verse': 16},
   'L2B20': {'book': BB.Isaiah, 'chapter': 41, 'verse': 23},
   'L2B21': {'book': BB.Isaiah, 'chapter': 46, 'verse': 9},
   'L2B28': {'book': BB.Isaiah, 'chapter': 13, 'verse': 19},
   'L2B29': {'book': BB.Jeremiah, 'chapter': 51, 'verse': 37},
   'L2B40': {'book': BB.Isaiah, 'chapter': 45, 'verse': 1},
   'L2B48': {'book': BB.Amos, 'chapter': 3, 'verse': 7},
   'L2B51': {'book': BB.Corinthians1, 'chapter': 10, 'verse': 11},
   'L2B54': {'book': BB.Hebrews, 'chapter': 4, 'verse': 12},
};


//'': {'book': BB., 'chapter': , 'verse': },